//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//


package test.integration.soap;

import javax.xml.ws.WebFault;

@WebFault(name = "ApplicationSoapWrapperException", targetNamespace = "http://ws.sample.co.uk/")
public class ApplicationSoapWrapperException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private ApplicationSoapWrapperException faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public ApplicationSoapWrapperException_Exception(String message, ApplicationSoapWrapperException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ApplicationSoapWrapperException_Exception(String message, ApplicationSoapWrapperException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: test.integration.soap.ApplicationSoapWrapperException
     */
    public ApplicationSoapWrapperException getFaultInfo() {
        return faultInfo;
    }

}
