//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//


package test.integration.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "IfSoapWebService", targetNamespace = "http://ws.sample.co.uk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IfSoapWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns test.integration.soap.WsAnnouncementListReturnDTO
     * @throws ApplicationSoapWrapperException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "callWsAnnouncementList", targetNamespace = "http://ws.sample.co.uk/", className = "test.integration.soap.CallWsAnnouncementList")
    @ResponseWrapper(localName = "callWsAnnouncementListResponse", targetNamespace = "http://ws.sample.co.uk/", className = "test.integration.soap.CallWsAnnouncementListResponse")
    @Action(input = "http://ws.sample.co.uk/IfSoapWebService/callWsAnnouncementListRequest", output = "http://ws.sample.co.uk/IfSoapWebService/callWsAnnouncementListResponse", fault = {
        @FaultAction(className = ApplicationSoapWrapperException_Exception.class, value = "http://ws.sample.co.uk/IfSoapWebService/callWsAnnouncementList/Fault/ApplicationSoapWrapperException")
    })
    public WsAnnouncementListReturnDTO callWsAnnouncementList(
        @WebParam(name = "arg0", targetNamespace = "")
        WsAnnouncementListRequestDTO arg0)
        throws ApplicationSoapWrapperException_Exception
    ;

}
