//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//


package test.integration.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the test.integration.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CallWsAnnouncementListResponse_QNAME = new QName("http://ws.sample.co.uk/", "callWsAnnouncementListResponse");
    private final static QName _CallWsAnnouncementList_QNAME = new QName("http://ws.sample.co.uk/", "callWsAnnouncementList");
    private final static QName _ApplicationSoapWrapperException_QNAME = new QName("http://ws.sample.co.uk/", "ApplicationSoapWrapperException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: test.integration.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationSoapWrapperException }
     * 
     */
    public ApplicationSoapWrapperException createApplicationSoapWrapperException() {
        return new ApplicationSoapWrapperException();
    }

    /**
     * Create an instance of {@link CallWsAnnouncementListResponse }
     * 
     */
    public CallWsAnnouncementListResponse createCallWsAnnouncementListResponse() {
        return new CallWsAnnouncementListResponse();
    }

    /**
     * Create an instance of {@link CallWsAnnouncementList }
     * 
     */
    public CallWsAnnouncementList createCallWsAnnouncementList() {
        return new CallWsAnnouncementList();
    }

    /**
     * Create an instance of {@link WsAnnouncementListBean }
     * 
     */
    public WsAnnouncementListBean createWsAnnouncementListBean() {
        return new WsAnnouncementListBean();
    }

    /**
     * Create an instance of {@link SoapBaseRequestDTO }
     * 
     */
    public SoapBaseRequestDTO createSoapBaseRequestDTO() {
        return new SoapBaseRequestDTO();
    }

    /**
     * Create an instance of {@link WsAnnouncementListRequestDTO }
     * 
     */
    public WsAnnouncementListRequestDTO createWsAnnouncementListRequestDTO() {
        return new WsAnnouncementListRequestDTO();
    }

    /**
     * Create an instance of {@link WsAnnouncementListReturnDTO }
     * 
     */
    public WsAnnouncementListReturnDTO createWsAnnouncementListReturnDTO() {
        return new WsAnnouncementListReturnDTO();
    }

    /**
     * Create an instance of {@link SoapBaseReturnDTO }
     * 
     */
    public SoapBaseReturnDTO createSoapBaseReturnDTO() {
        return new SoapBaseReturnDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallWsAnnouncementListResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.sample.co.uk/", name = "callWsAnnouncementListResponse")
    public JAXBElement<CallWsAnnouncementListResponse> createCallWsAnnouncementListResponse(CallWsAnnouncementListResponse value) {
        return new JAXBElement<CallWsAnnouncementListResponse>(_CallWsAnnouncementListResponse_QNAME, CallWsAnnouncementListResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CallWsAnnouncementList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.sample.co.uk/", name = "callWsAnnouncementList")
    public JAXBElement<CallWsAnnouncementList> createCallWsAnnouncementList(CallWsAnnouncementList value) {
        return new JAXBElement<CallWsAnnouncementList>(_CallWsAnnouncementList_QNAME, CallWsAnnouncementList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationSoapWrapperException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.sample.co.uk/", name = "ApplicationSoapWrapperException")
    public JAXBElement<ApplicationSoapWrapperException> createApplicationSoapWrapperException(ApplicationSoapWrapperException value) {
        return new JAXBElement<ApplicationSoapWrapperException>(_ApplicationSoapWrapperException_QNAME, ApplicationSoapWrapperException.class, null, value);
    }

}
