//
// Generated By:JAX-WS RI 2.2.9-b130926.1035 (JAXB RI IBM 2.2.8-b130911.1802)
//


package test.integration.soap;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wsAnnouncementListReturnDTO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsAnnouncementListReturnDTO">
 *   &lt;complexContent>
 *     &lt;extension base="{http://ws.sample.co.uk/}soapBaseReturnDTO">
 *       &lt;sequence>
 *         &lt;element name="announcements" type="{http://ws.sample.co.uk/}wsAnnouncementListBean" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsAnnouncementListReturnDTO", propOrder = {
    "announcements"
})
public class WsAnnouncementListReturnDTO
    extends SoapBaseReturnDTO
{

    @XmlElement(nillable = true)
    protected List<WsAnnouncementListBean> announcements;

    /**
     * Gets the value of the announcements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the announcements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnouncements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WsAnnouncementListBean }
     * 
     * 
     */
    public List<WsAnnouncementListBean> getAnnouncements() {
        if (announcements == null) {
            announcements = new ArrayList<WsAnnouncementListBean>();
        }
        return this.announcements;
    }

}
